import React from 'react';
import styled from 'styled-components';
import { useTranslation } from 'react-i18next';
import { Card, Card2, Heading, CardBody } from '~/ui';
import Page from '~/components/layout/Page';

const AI = () => {
  const { t } = useTranslation();

  return (
    <Page>
      <Card2 style={{ width: '100%' }}>
        <Heading as="h2" size="xl" style={{ textAlign: 'center', marginTop: 15, padding: 20 }}>
          {t('Arken AI')}
        </Heading>
        <hr />
        <CardBody>
          <p>
            Arken Realms is the first AI-powered fantasy omniverse. All of our artwork will be generated by AI using
            community suggested prompts. These prompts will be open to all dark fantasy lovers to enjoy and play with.
            All Arken Realms art will continue to be refined so we are always the number one destination for dark
            fantasy in the metaverse.
            <br />
            <br />
            Eventually, the DAO will be integrated into all refinement decisions. What that means is the token holders
            will vote if they want to improve the concept / model of a particular item/zone/character/etc. Until then,
            most discussion and voting will take place in Telegram/Discord.
            <br />
            <br />
            We've already begun the process of AI generating our Runeform items,{' '}
            <a href="/news/new-age-of-game-items" rel="noreferrer noopener" target="_blank">
              as detailed in this announcement
            </a>
            . Every item dropped or crafted in Arken games will come with a unique skin that nobody else has.
          </p>
        </CardBody>
      </Card2>
    </Page>
  );
};

export default AI;
