import { Team } from './types'

const teams: Team[] = [
  {
    id: 1,
    name: 'The First Order',
    description: 'Scholars and time mages brought together by Bin Zy in the service of Zeno.',
    images: {
      lg: 'the-first-ones.png',
      md: 'the-first-ones.png',
      sm: 'the-first-ones.png',
      alt: 'the-first-ones.png',
      ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/the-first-ones.png',
    },
    background: 'guild.svg',
    textColor: '#fff',
  },
  {
    id: 2,
    name: 'The Archivists',
    description: "Keepers of lore and the guardians of Haerra's history.",
    images: {
      lg: 'the-archivists.png',
      md: 'the-archivists.png',
      sm: 'the-archivists.png',
      alt: 'the-archivists.png',
      ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/the-archivists.png',
    },
    background: 'guild.svg',
    textColor: '#fff',
  },
  {
    id: 3,
    name: 'Knights of Westmarch',
    description: 'Knights of purity and enforcers of justice.',
    images: {
      lg: 'knights-of-westmarch.png',
      md: 'knights-of-westmarch.png',
      sm: 'knights-of-westmarch.png',
      alt: 'knights-of-westmarch.png',
      ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/knights-of-westmarch.png',
    },
    background: 'guild.svg',
    textColor: '#fff',
  },
  {
    id: 4,
    name: 'The Protectors',
    description:
      'After the destruction of the Worldstone, these dark souls serve Azorag in the destruction of all living things.',
    images: {
      lg: 'the-protectors.png',
      md: 'the-protectors.png',
      sm: 'the-protectors.png',
      alt: 'the-protectors.png',
      ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/the-protectors.png',
    },
    background: 'guild.svg',
    textColor: '#fff',
  },
  {
    id: 5,
    name: 'The Destroyers',
    description:
      'After the destruction of the Worldstone, these survivors banded together to find and protect the Worldstone shards from falling into the hands of evil.',
    images: {
      lg: 'the-destroyers.png',
      md: 'the-destroyers.png',
      sm: 'the-destroyers.png',
      alt: 'the-destroyers.png',
      ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/the-destroyers.png',
    },
    background: 'guild.svg',
    textColor: '#fff',
  },
  {
    id: 6,
    name: 'Drocos Legion',
    description:
      'Dragon riders and defenders, this elite group seeks to defend the few remaining dragons from the onslaught of humanoids.',
    images: {
      lg: 'drocos-legion.png',
      md: 'drocos-legion.png',
      sm: 'drocos-legion.png',
      alt: 'drocos-legion.png',
      ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/drocos-legion.png',
    },
    background: 'guild.svg',
    textColor: '#fff',
  },
  {
    id: 7,
    name: 'Heden Saf',
    description:
      'A group of clerics and miracle-workers dedicated to the Cull: the eradication of all non-energy users in Haerra.',
    images: {
      lg: 'heden-saf.png',
      md: 'heden-saf.png',
      sm: 'heden-saf.png',
      alt: 'heden-saf.png',
      ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/heden-saf.png',
    },
    background: 'guild.svg',
    textColor: '#fff',
  },
  {
    id: 8,
    name: 'Radiant Viziers',
    description:
      'The Radiant Viziers are a group of expert fighters dedicated to Relia, with bastions of influence all over Haerra.',
    images: {
      lg: 'radiant-viziers.png',
      md: 'radiant-viziers.png',
      sm: 'radiant-viziers.png',
      alt: 'radiant-viziers.png',
      ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/radiant-viziers.png',
    },
    background: 'guild.svg',
    textColor: '#fff',
  },
  // {
  //   id: 7,
  //   name: 'Seers of Hexgard',
  //   description:
  //     'Deep within the twisted forests of Hexgard, these fearsome oracles seek wisdom from the otherworldly.',
  //   images: {
  //     lg: 'seers-of-hexgard.png',
  //     md: 'seers-of-hexgard.png',
  //     sm: 'seers-of-hexgard.png',
  //     alt: 'seers-of-hexgard.png',
  //     ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/seers-of-hexgard.png',
  //   },
  //   background: 'guild.svg',
  //   textColor: '#fff',
  //   users: 0,
  //   activeMemberCount: 0,
  //   memberCount: 0,
  //   points: 0,
  // },
  // {
  //   id: 8,
  //   name: 'Guildmasters of Qiddir',
  //   description:
  //     'A people of order and expertise, dedicated to crafting marvelous and practical inventions to solve Haerra\'s problems.',
  //   images: {
  //     lg: 'guildmasters-of-qiddir.png',
  //     md: 'guildmasters-of-qiddir.png',
  //     sm: 'guildmasters-of-qiddir.png',
  //     alt: 'guildmasters-of-qiddir.png',
  //     ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/guildmasters-of-qiddir.png',
  //   },
  //   background: 'guild.svg',
  //   textColor: '#fff',
  //   users: 0,
  //   activeMemberCount: 0,
  //   memberCount: 0,
  //   points: 0,
  // },
  // {
  //   id: 9,
  //   name: 'Alchemists of Tabr',
  //   description:
  //     'A people of chaos and unchained scientific pursuit, dedicated to wild progress and free innovation.',
  //   images: {
  //     lg: 'alchemists-of-tabr.png',
  //     md: 'alchemists-of-tabr.png',
  //     sm: 'alchemists-of-tabr.png',
  //     alt: 'alchemists-of-tabr.png',
  //     ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/alchemists-of-tabr.png',
  //   },
  //   background: 'guild.svg',
  //   textColor: '#fff',
  //   users: 0,
  //   activeMemberCount: 0,
  //   memberCount: 0,
  //   points: 0,
  // },
  // {
  //   id: 6,
  //   name: 'Brotherhood of Vtello',
  //   description:
  //     'The most skilled assassins in Haerra, bound together by fraternity and coin.',
  //   images: {
  //     lg: 'brotherhood-of-vtello.png',
  //     md: 'brotherhood-of-vtello.png',
  //     sm: 'brotherhood-of-vtello.png',
  //     alt: 'brotherhood-of-vtello.png',
  //     ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/brotherhood-of-vtello.png',
  //   },
  //   background: 'guild.svg',
  //   textColor: '#fff',
  //   users: 0,
  //   activeMemberCount: 0,
  //   memberCount: 0,
  //   points: 0,
  // },
  // {
  //   id: 7,
  //   name: 'Forest Dwellers of Tilia',
  //   description:
  //     'Legendary archers and protectors of the Ashyrah forests.',
  //   images: {
  //     lg: 'forest-dwellers-of-tilia.png',
  //     md: 'forest-dwellers-of-tilia.png',
  //     sm: 'forest-dwellers-of-tilia.png',
  //     alt: 'forest-dwellers-of-tilia.png',
  //     ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/forest-dwellers-of-tilia.png',
  //   },
  //   background: 'guild.svg',
  //   textColor: '#fff',
  //   users: 0,
  //   activeMemberCount: 0,
  //   memberCount: 0,
  //   points: 0,
  // },
  // {
  //   id: 7,
  //   name: 'Tribe of the Great Faytree',
  //   description:
  //     'Protectors of the Faytree and speakers of the wild.',
  //   images: {
  //     lg: 'tribe-of-the-great-faytree.png',
  //     md: 'tribe-of-the-great-faytree.png',
  //     sm: 'tribe-of-the-great-faytree.png',
  //     alt: 'tribe-of-the-great-faytree.png',
  //     ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/tribe-of-the-great-faytree.png',
  //   },
  //   background: 'guild.svg',
  //   textColor: '#fff',
  //   users: 0,
  //   activeMemberCount: 0,
  //   memberCount: 0,
  //   points: 0,
  // },
  // {
  //   id: 7,
  //   name: 'Ragor Necrologists',
  //   description:
  //     'Mysterious scholars of the undead and stewards of the spirit world.',
  //   images: {
  //     lg: 'ragor-necrologists.png',
  //     md: 'ragor-necrologists.png',
  //     sm: 'ragor-necrologists.png',
  //     alt: 'ragor-necrologists.png',
  //     ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/ragor-necrologists.png',
  //   },
  //   background: 'guild.svg',
  //   textColor: '#fff',
  //   users: 0,
  //   activeMemberCount: 0,
  //   memberCount: 0,
  //   points: 0,
  // },
  // {
  //   id: 7,
  //   name: 'The Tribe of Carnage',
  //   description:
  //     '	One with blood and blade, the rage of these barbarians knows no bounds.',
  //   images: {
  //     lg: 'the-tribe-of-carnage.png',
  //     md: 'the-tribe-of-carnage.png',
  //     sm: 'the-tribe-of-carnage.png',
  //     alt: 'the-tribe-of-carnage.png',
  //     ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/the-tribe-of-carnage.png',
  //   },
  //   background: 'guild.svg',
  //   textColor: '#fff',
  //   users: 0,
  //   activeMemberCount: 0,
  //   memberCount: 0,
  //   points: 0,
  // },
  // {
  //   id: 7,
  //   name: 'Paladins of Ashyrah',
  //   description:
  //     'A group of upright fighters who adhere to a strict code instead of the dictates of a single religion.',
  //   images: {
  //     lg: 'the-tribe-of-carnage.png',
  //     md: 'the-tribe-of-carnage.png',
  //     sm: 'the-tribe-of-carnage.png',
  //     alt: 'the-tribe-of-carnage.png',
  //     ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/the-tribe-of-carnage.png',
  //   },
  //   background: 'guild.svg',
  //   textColor: '#fff',
  //   users: 0,
  //   activeMemberCount: 0,
  //   memberCount: 0,
  //   points: 0,
  // },
  // {
  //   id: 7,
  //   name: 'Wardens of Irondell',
  //   description:
  //     'Watchers over the Fayhelm forests and guardians of Irondell.',
  //   images: {
  //     lg: 'wardens-of-irondell.png',
  //     md: 'wardens-of-irondell.png',
  //     sm: 'wardens-of-irondell.png',
  //     alt: 'wardens-of-irondell.png',
  //     ipfs: process.env.REACT_APP_PUBLIC_URL + 'images/teams/wardens-of-irondell.png',
  //   },
  //   background: 'guild.svg',
  //   textColor: '#fff',
  //   users: 0,
  //   activeMemberCount: 0,
  //   memberCount: 0,
  //   points: 0,
  // },
]

export default teams
